---
- name: deploy nginx
  hosts: all
  vars:
          web_server: apache2
          web_server_pre: apache2
  tasks:
          - name: install {{ web_server }}
            package:
                    name: "{{ web_server }}"
                    state: latest
          - name: start and enable {{ web_server }}
            service:
                    name: "{{ web_server }}"
                    enabled: true
                    state: started
...
